import Phaser from 'phaser';
import { SCENES, GAME_WIDTH, GAME_HEIGHT } from '../config.js';
import Playables from '../systems/Playables.js';
import I18n from '../systems/I18n.js';

export default class PreloadScene extends Phaser.Scene {
  constructor() {
    super(SCENES.PRELOAD);
  }

  preload() {
    const w = GAME_WIDTH;
    const h = GAME_HEIGHT;

    const barBg = this.add.rectangle(w / 2, h / 2, 400, 8, 0x2a1a2a);
    const bar = this.add.rectangle(w / 2 - 200, h / 2, 0, 8, 0xe8b96a).setOrigin(0, 0.5);
    this.add.text(w / 2, h / 2 - 30, I18n.t('preload.loading'), {
      fontFamily: 'sans-serif',
      fontSize: '16px',
      color: '#e8dccb',
    }).setOrigin(0.5);

    // YT Playables certification: firstFrameReady() MUST fire once we
    // are visibly rendering a loading UI. Call it at the end of this
    // frame so Phaser has committed the draw.
    this.time.delayedCall(0, () => Playables.firstFrameReady());

    this.load.on('progress', (p) => {
      bar.width = 400 * p;
    });

    this.load.image('bg-apartment', 'assets/images/bg/01_apartment_livingroom.png');
    this.load.image('bg-stairwell', 'assets/images/bg/02_stairwell.png');
    this.load.image('bg-alley-clear', 'assets/images/bg/03_alley_dusk_clear.png');
    this.load.image('bg-alley-rain', 'assets/images/bg/04_alley_dusk_rain.png');
    this.load.image('bg-alley-night-market', 'assets/images/bg/05_alley_dusk_night_market.png');
    this.load.image('bg-yard-ending', 'assets/images/bg/06_yard_ending.png');

    this.load.image('player-idle', 'assets/images/char/player_front_idle.png');
    this.load.image('player-walk-1', 'assets/images/char/player_walk_side_01.png');
    this.load.image('player-walk-2', 'assets/images/char/player_walk_side_02.png');
    this.load.image('player-walk-3', 'assets/images/char/player_walk_side_03.png');
    this.load.image('player-walk-4', 'assets/images/char/player_walk_side_04.png');
    this.load.image('player-run', 'assets/images/char/player_run_side.png');
    this.load.image('mom-angry', 'assets/images/char/mom_angry.png');
    this.load.image('mom-proud', 'assets/images/char/mom_proud.png');
    this.load.image('mom-satisfied', 'assets/images/char/mom_satisfied.png');

    this.load.image('truck-far', 'assets/images/char/truck_far.png');
    this.load.image('truck-mid', 'assets/images/char/truck_mid.png');

    // Audio loads — optional. Failed loads are expected before the user drops
    // Suno exports + field recordings in; the game falls back to synth + procedural SFX.
    this.load.audio('bgm-main', [
      'assets/audio/music/bgm_main.mp3',
      'assets/audio/music/bgm_main.ogg',
    ]);
    this.load.audio('bgm-tension', [
      'assets/audio/music/bgm_tension.mp3',
      'assets/audio/music/bgm_tension.ogg',
    ]);
    this.load.audio('bgm-ending', [
      'assets/audio/music/bgm_ending.mp3',
      'assets/audio/music/bgm_ending.ogg',
    ]);
    this.load.audio('truck-real', [
      'assets/audio/sfx/truck_recording.mp3',
      'assets/audio/sfx/truck_recording.ogg',
    ]);
    // Short-key SFX (throw/hit/miss/...) are the names Sfx.js plays. Map
    // each to a file in assets/audio/sfx/ generated by `npm run build:sfx`
    // (trimmed sources + jsfxr-style synthesis per assets/prompts/06_sfx_list.md).
    // Missing keys fall through to Sfx.js's procedural WebAudio fallbacks.
    const SFX_FILE_MAP = {
      throw: 'sfx_bag_drop',
      hit: 'sfx_bag_hit_metal',
      miss: 'sfx_qte_fail',
      ping: 'sfx_phone_notification',
      tick: 'sfx_score_count',
      scroll: 'sfx_door_slide',
      static: 'sfx_tv_static_bg',
      step: 'sfx_footsteps_loop',
    };
    for (const [key, file] of Object.entries(SFX_FILE_MAP)) {
      this.load.audio(`sfx-${key}`, `assets/audio/sfx/${file}.mp3`);
    }
    // Extra scene-specific SFX — no Sfx.js key, played directly by scene code.
    this.load.audio('sfx-truck-engine', 'assets/audio/sfx/sfx_truck_engine_loop.mp3');
    this.load.audio('sfx-truck-brake', 'assets/audio/sfx/sfx_truck_brake.mp3');
    this.load.audio('sfx-qte-success', 'assets/audio/sfx/sfx_qte_success.mp3');
    this.load.audio('sfx-run', 'assets/audio/sfx/sfx_running_loop.mp3');

    // Mom voice lines — per-day caught/missed × two languages. ResultScene
    // picks the lang suffix at play time based on I18n.lang.
    for (let day = 1; day <= 5; day++) {
      for (const outcome of ['caught', 'missed']) {
        for (const lang of ['zh', 'en']) {
          this.load.audio(`mom-d${day}-${outcome}-${lang}`,
            `assets/audio/voice/mom_d${day}_${outcome}_${lang}.mp3`);
        }
      }
    }
    // Encounter override voices (張阿姨 scold / 黃爺爺 proud / 陳奶奶 mild scold).
    for (const kind of ['zhang_scold', 'huang_proud', 'chen_miss']) {
      for (const lang of ['zh', 'en']) {
        this.load.audio(`mom-enc-${kind}-${lang}`,
          `assets/audio/voice/mom_enc_${kind}_${lang}.mp3`);
      }
    }

    // Image loads can silently fail on bad paths — surface that in the console.
    // For audio, we expect 404s before recording + music are ready.
    this.load.on('loaderror', (file) => {
      if (file.type !== 'audio') {
        console.warn('[preload] asset missing:', file.src);
      }
    });
  }

  create() {
    this.scene.start(SCENES.TITLE);
  }
}
